# -*- coding: utf-8 -*-
"""Prompting_with_API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YsuMMBbcWvyicbvfI2j6cdDkf2M-T20K

# Applied Generative AI
Instructor: Prof. Dehghani
Welcome to the Applied Generative AI course. In this course, we will explore the foundations and applications of Generative AI using tools like OpenAI's API. By the end of this session, you will:

🟢 Understand how to set up and connect to OpenAI's API.
🌟 Learn about the roles (System, Assistant, User) in prompt design.
✨ Generate text, images, and vector embeddings programmatically.
🔧 Explore fine-tuning to customize AI models for specific tasks.
Let’s get started with setting up the OpenAI API!
"""

# Install the OpenAI Python SDK
# This library allows us to interact with OpenAI's API for text, images, and embeddings.
!pip install openai==0.28

from google.colab import userdata
import openai

# Retrieve the key from Colab secrets
openai.api_key = userdata.get("OPENAI_API_KEY")

# Confirm the key was loaded (for debugging only; don’t print your real key in shared notebooks!)
print("Key loaded:", "Yes" if openai.api_key else "No")

"""🎯 Prompt Playground: Understanding Roles
In OpenAI's API, you interact with the model using roles, which define the flow of the conversation:

➡️ System: Sets the behavior and tone of the assistant (e.g., "You are a cheerful assistant.").
➡️ User: Represents the input or question from the user (e.g., "What is AI?").
➡️ Assistant: Automatically generated responses based on the system and user inputs.
💡 Why Roles Matter: Roles help control the assistant's personality and the quality of responses. For example:

A system message like "You are a strict teacher" makes the assistant respond more formally.
A system message like "You are a friendly chatbot" leads to casual responses.
Let’s see how these roles work in the next cell!

## Example 1: Without Assistant Role
"""

import openai

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What is the capital of France?"}
    ]
)

print(response['choices'][0]['message']['content'])

"""# Example 2: With Assistant Role"""

# Demonstrating roles in OpenAI's API with the assistant role

# Define the conversation including a predefined assistant response
messages = [
    {"role": "system", "content": "You are a math tutor who explains problems step by step."},  # System role sets the behavior
    {"role": "user", "content": "Solve for x: 2x + 5 = 15"},  # User question
    {"role": "assistant", "content": "To solve for x: \n1. Subtract 5 from both sides: 2x = 10\n2. Divide both sides by 2: x = 5"}  # Predefined assistant response
]

# Send the conversation to the API
response = openai.ChatCompletion.create(
    model="gpt-4",  # Use the chosen model
    messages=messages  # Pass the conversation
)

# Print the assistant's response
print("Assistant's Response:", response['choices'][0]['message']['content'])

"""🧮 Hands-On"""

# ++++ Hands-On: Complete the Roles ++++

# Define the conversation using the role structure
messages = [
    {"role": "----", "content": "You are a math tutor who explains concepts clearly and step by step."},  # Complete the system role
    {"role": "----", "content": "How do you calculate the arithmetic mean of a set of numbers?"},  # Complete the user role
    {"role": "----", "content": "To calculate the arithmetic mean:\n"
                                "1. Add all the numbers in the set.\n"
                                "2. Divide the sum by the number of numbers.\n\n"
                                "For example, for 10, 20, and 30:\n"
                                "Mean = (10 + 20 + 30) / 3 = 60 / 3 = 20."
                                }  # Optional predefined assistant response
]

# Uncomment the code below after completing the placeholders
# response = openai.ChatCompletion.create(
#     model="gpt-4",  # Specify the model
#     messages=messages  # Pass the completed conversation
# )
# print("Assistant's Response:", response['choices'][0]['message']['content'])

"""Exercise 1: Simple Q&A with System + User Roles
👉 Task:
Write a prompt that asks the assistant to behave like a science teacher, then ask it a science-related question.
"""

# 🧠 Define your own roles and prompt below
messages = [
    {"role": "------", "content": "You are a [insert role/personality, e.g., 'science teacher', 'debate coach']."},
    {"role": "------", "content": "Ask your question here, e.g., 'Explain how photosynthesis works.'"}
]

# 🧠 Call the OpenAI API with your customized prompt
response = openai.ChatCompletion.create(
    model="gpt-4",
    messages=messages
)

# 🧠 Print the model's response
print("Assistant's Response:", response['choices'][0]['message']['content'])

"""✍️ Exercise 2: Give a prompt of your choice.
👉 Task:
Now write your own custom prompt. Use any role, any question — be creative!
"""

# Replace with your own prompt idea!
messages = [
    {"role": "system", "content": "You are a ____."},
    {"role": "user", "content": "____?"}
]

response = openai.ChatCompletion.create(
    model="gpt-4",
    messages=messages
)

print("Assistant's Response:", response['choices'][0]['message']['content'])